# TODO : fix the bug which training is not process
ARG BASE_IMAGE=python:3.6
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
FROM ${BASE_IMAGE}

WORKDIR /workspace

# install python packages
RUN bash install.sh

# copy entry.sh
ADD ./setup.sh /workspace
