ARG BASE_IMAGE=python:3.7
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
FROM ${BASE_IMAGE}

WORKDIR /workspace

# install python packages
RUN pip install streamlit boto3

# copy entry.sh
ADD ./entry.sh /workspace
